### ISSUE TITLE
wielrennentest

### ISSUE THREAD

**Issue by Zuijdam** [geensnor/SnorBot#108]
wielrennentest geeft een error, en die kan ik niet fixen :( kun jij er naar kijken?

**Comment by reithose** [comment]
Oeh, dat is inderdaad niet goed. Zal er straks eens naar kijken!

**Comment by reithose** [comment]
https://github.com/geensnor/SnorBot/commit/ed929a90a85ee73626bd446dd62258ffb35eeb03
