### ISSUE TITLE
Leeftijd niet goed op verjaardag

### ISSUE THREAD

**Issue by reithose** [geensnor/SnorBot#43]
Op de dag dat iemand jarig is, wordt de leeftijd niet goed weergegeven. Er moet eigenlijk een jaar bij.

**Comment by Zuijdam** [comment]
Oei...dat is niet fraai! Dank voor het melden, zonder de input van onze community (jij!) waren we nooit zo ver gekomen

**Comment by reithose** [comment]
Geen punt. Zo dragen we allemaal ons steentje bij.

Ik denk dat ik ook wel weet waar het probleem zit. Hier gaat waarschijnlijk iets niet goed met de leeftijd berekenen in seconden en converteren naar jaren:

```php
$persoon["leeftijd"] = floor(($referentieDatum - strtotime($this->geboortedatums[$key]->geboortedatum))/31557600);

**Comment by reithose** [comment]
Is gefixed in #44
