### ISSUE TITLE
Bitcoin percentage blijft 0%

### ISSUE THREAD

**Issue by Zuijdam** [geensnor/SnorBot#49]
Bij het opvragen van bitcoin koers blijft percentage van de wijziging altijd op 0%

Reproductie: /bitcoin 
Resultaat: huidige koers + 0% in afgelopen 24h
Verwachte resultaat: huidige koers + percentage bij/af in afgelopen 24h

**Comment by reithose** [comment]
API waar we gebruik van maken is kapot: https://api.bitvavo.com/v1/currencies. In het veld "pct_change_24hr" staat bij Bitcoin gewoon 0.
