### ISSUE TITLE
/crypto maken

### ISSUE THREAD

**Issue by reithose** [geensnor/SnorBot#63]
Eén commando om alle cryptocurrency te tonen.

**Comment by Zuijdam** [comment]
Goed idee...ik heb /crypto gemaakt. Is dat wat? Staat op test en heb PR gemaakt

**Comment by reithose** [comment]
Ja, maar ik ben nog niet helemaal wild van de opmaak van het antwoord. Er staat nu nog zo'n verdwaalde | tussen en het gebruik van newlines laat ook nog wel wat te wensen over.

**Comment by reithose** [comment]
Nu is hij prima
